name: test sparse-checkout

on:
  workflow_dispatch:
  
jobs:
  TestCheckout:
    runs-on: [ self-hosted ]
    
    steps:
    - uses: actions/checkout@v3
      with:
        sparse-checkout: |
          Folder1
        
    - name: display contents
      run: |
        get-childitem .\ -recurse -verbose
      shell: powershell
